on:
  push:
    branches: [  master ]
name: CI - PROD

env:
  host: ${{ secrets.IP_SERVER_PROD }}
  key: ${{ secrets.SSH_KEY_SOFTLINK_PLURIZA }}
  port: ${{ secrets.SSSH_PORT_PROD }}
  username: ${{ secrets.VM_USER }}

jobs:
  deployProduction:
    name: Deploy to prod
    runs-on: ubuntu-latest
    steps:
    - run: echo ${#host}
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Configue credentials
      uses: appleboy/ssh-action@v0.1.10

      with:
        host: ${{ secrets.IP_SERVER_PROD }}
        key: ${{ secrets.SSH_KEY_SOFTLINK_PLURIZA }}
        port: ${{ secrets.SSSH_PORT_PROD }}
        username: ${{ secrets.VM_USER }}
        script: |
          cd ${{ secrets.PROJECT_PATH }}
          sh start.sh


