on:
  push:
    branches: [  master ]
name: CI - PROD

permissions:
  id-token: write
  contents: read

jobs:
  deployProduction:
    name: Deploy to prod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - run: echo ${{ vars.REPO_OWNER }}
    - name: Configue credentials
      uses: appleboy/ssh-action@v0.1.10
      env:
        ORIGIN: ${{ secrets.IP_SERVER_PROD }}
        SSHKEY: ${{ secrets.SSH_KEY_SOFTLINK_PLURIZA }}
        PORT: ${{ secrets.SSSH_PORT_PROD }}
        USER: ${{ secrets.VM_USER }}
      with:
        host: ${{ env.IP_SERVER_PROD }}
        key: ${{ env.SSH_KEY_SOFTLINK_PLURIZA }}
        port: ${{ env.SSSH_PORT_PROD }}
        username: ${{ env.VM_USER }}
        script: |
          cd ${{ secrets.PROJECT_PATH }}
          sh start.sh


