on:
  push:
    branches: [  master ]
name: CI - PROD


jobs:
  deployProduction:
    name: Deploy to prod
    runs-on: ubuntu-latest
    environment: wafi
    steps:
    - run: echo ${#host}
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Configue credentials
      uses: appleboy/ssh-action@v0.1.10
      env:
        host: ${{ secrets.IP_SERVER_PROD }}
        key: ${{ secrets.SSH_KEY_SOFTLINK_PLURIZA }}
        port: ${{ secrets.SSSH_PORT_PROD }}
        username: ${{ secrets.VM_USER }}
        path: ${{ secrets.PROJECT_PATH }}
      with:
        host: ${{ env.host }}
        key: ${{ env.key }}
        port: ${{ env.port }}
        username: ${{ env.username }}
        script: |
          cd ${{ env.path }}
          sh start.sh


