on:
  push:
    branches: [  master ]
name: CI - PROD

permissions:
  id-token: write
  contents: read

jobs:
  deployProduction:
    name: Deploy to prod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: Configue credentials
      uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
      env:
        ORIGIN: ${{ secrets.IP_SERVER_PROD }}
        SSHKEY: ${{ secrets.SSH_KEY_SOFTLINK_PLURIZA }}
        PORT: ${{ secrets.SSSH_PORT_PROD }}
        USER: ${{ secrets.VM_USER }}
      with:
        ORIGIN: ${{ env.IP_SERVER_PROD }}
        SSHKEY: ${{ env.SSH_KEY_SOFTLINK_PLURIZA }}
        NAME: production
        PORT: ${{ env.SSSH_PORT_PROD }}
        USER: ${{ env.VM_USER }}
    - name: "Connect to VM"
      run: ssh production
    - name: "Acces to project directory"
      run: cd ${{ secrets.PROJECT_PATH }}
    - name: "Running process"
      run: sh start.sh


